# Generated by Django 5.1.1 on 2024-10-08 22:27

import django.db.models.deletion
import website.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stimulus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField()),
                ('stimulus_content', models.CharField(max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(default=website.models.generate_link, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uname', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=200)),
                ('passwd', models.CharField(max_length=50)),
                ('creation_date', models.DateTimeField(auto_now=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('permission_lvl', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField()),
                ('avg_latency1', models.IntegerField()),
                ('avg_latency2', models.IntegerField()),
                ('avg_latency3', models.IntegerField()),
                ('avg_latency4', models.IntegerField()),
                ('avg_latency5', models.IntegerField()),
                ('avg_latency6', models.IntegerField()),
                ('amount_correct', models.IntegerField()),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.test')),
            ],
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response', models.CharField(max_length=10)),
                ('latency', models.IntegerField()),
                ('is_correct', models.BooleanField()),
                ('stimulus', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='website.stimulus')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.test')),
            ],
        ),
        migrations.AddField(
            model_name='test',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.user'),
        ),
    ]
