# Generated by Django 5.1.1 on 2024-10-05 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uname', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=200)),
                ('passwd', models.CharField(max_length=50)),
                ('creation_date', models.DateField()),
                ('last_login', models.DateTimeField()),
                ('permission_lvl', models.IntegerField(verbose_name=1)),
            ],
        ),
    ]
