# Generated by Django 5.1.2 on 2024-10-29 02:43

import django.db.models.deletion
import website.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Aggreagate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age_group', models.CharField(max_length=10)),
                ('avg_fourdigit_accuracy_1', models.FloatField(default=0, null=True)),
                ('avg_fourdigit_latency_1', models.IntegerField(default=0)),
                ('avg_fourdigit_accuracy_2', models.FloatField(default=0, null=True)),
                ('avg_fourdigit_latency_2', models.IntegerField(default=0)),
                ('avg_fourdigit_accuracy_3', models.FloatField(default=0, null=True)),
                ('avg_fourdigit_latency_3', models.IntegerField(default=0)),
                ('avg_fivedigit_accuracy_1', models.FloatField(default=0, null=True)),
                ('avg_fivedigit_latency_1', models.IntegerField(default=0)),
                ('avg_fivedigit_accuracy_2', models.FloatField(default=0, null=True)),
                ('avg_fivedigit_latency_2', models.IntegerField(default=0)),
                ('avg_fivedigit_accuracy_3', models.FloatField(default=0, null=True)),
                ('avg_fivedigit_latency_3', models.IntegerField(default=0)),
                ('avg_fourmixed_accuracy_1', models.FloatField(default=0, null=True)),
                ('avg_fourmixed_latency_1', models.IntegerField(default=0)),
                ('avg_fourmixed_accuracy_2', models.FloatField(default=0, null=True)),
                ('avg_fourmixed_latency_2', models.IntegerField(default=0)),
                ('avg_fourmixed_accuracy_3', models.FloatField(default=0, null=True)),
                ('avg_fourmixed_latency_3', models.IntegerField(default=0)),
                ('avg_fivemixed_accuracy_1', models.FloatField(default=0, null=True)),
                ('avg_fivemixed_latency_1', models.IntegerField(default=0)),
                ('avg_fivemixed_accuracy_2', models.FloatField(default=0, null=True)),
                ('avg_fivemixed_latency_2', models.IntegerField(default=0)),
                ('avg_fivemixed_accuracy_3', models.FloatField(default=0, null=True)),
                ('avg_fivemixed_latency_3', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Stimulus_Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stimulus_type', models.CharField(default='', max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Stimulus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stimulus_content', models.CharField(max_length=6)),
                ('stimulus_type', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='website.stimulus_type')),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(default=website.models.generate_link, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('started_at', models.DateTimeField(null=True)),
                ('finished_at', models.DateTimeField(null=True)),
                ('age', models.IntegerField(default=0)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fourdigit_accuracy_1', models.FloatField(default=0, null=True)),
                ('fourdigit_latency_1', models.IntegerField(default=0)),
                ('fourdigit_accuracy_2', models.FloatField(default=0, null=True)),
                ('fourdigit_latency_2', models.IntegerField(default=0)),
                ('fourdigit_accuracy_3', models.FloatField(default=0, null=True)),
                ('fourdigit_latency_3', models.IntegerField(default=0)),
                ('fivedigit_accuracy_1', models.FloatField(default=0, null=True)),
                ('fivedigit_latency_1', models.IntegerField(default=0)),
                ('fivedigit_accuracy_2', models.FloatField(default=0, null=True)),
                ('fivedigit_latency_2', models.IntegerField(default=0)),
                ('fivedigit_accuracy_3', models.FloatField(default=0, null=True)),
                ('fivedigit_latency_3', models.IntegerField(default=0)),
                ('fourmixed_accuracy_1', models.FloatField(default=0, null=True)),
                ('fourmixed_latency_1', models.IntegerField(default=0)),
                ('fourmixed_accuracy_2', models.FloatField(default=0, null=True)),
                ('fourmixed_latency_2', models.IntegerField(default=0)),
                ('fourmixed_accuracy_3', models.FloatField(default=0, null=True)),
                ('fourmixed_latency_3', models.IntegerField(default=0)),
                ('fivemixed_accuracy_1', models.FloatField(default=0, null=True)),
                ('fivemixed_latency_1', models.IntegerField(default=0)),
                ('fivemixed_accuracy_2', models.FloatField(default=0, null=True)),
                ('fivemixed_latency_2', models.IntegerField(default=0)),
                ('fivemixed_accuracy_3', models.FloatField(default=0, null=True)),
                ('fivemixed_latency_3', models.IntegerField(default=0)),
                ('amount_correct', models.IntegerField(default=0)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.test')),
            ],
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response', models.CharField(default='', max_length=5)),
                ('time_submitted', models.DateTimeField(null=True)),
                ('response_position', models.IntegerField(default=0)),
                ('stimulus', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='website.stimulus')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.test')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=50)),
                ('message', models.CharField(max_length=100)),
                ('time_created', models.DateTimeField(auto_now=True)),
                ('is_dismissed', models.BooleanField(default=False)),
                ('test', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='website.test')),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('general', 'General Issue'), ('technical', 'Technical'), ('account', 'Account Management'), ('bug/error', 'Bug/Error Report')], max_length=50)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
