# Generated by Django 5.1.1 on 2024-10-05 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='permission_lvl',
            field=models.IntegerField(),
        ),
    ]
