# Generated by Django 5.1.1 on 2024-10-10 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aggreagate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age_group', models.CharField(max_length=10)),
                ('avg_latency1', models.IntegerField(default=0)),
                ('avg_latency2', models.IntegerField(default=0)),
                ('avg_latency3', models.IntegerField(default=0)),
                ('avg_latency4', models.IntegerField(default=0)),
                ('avg_latency5', models.IntegerField(default=0)),
                ('avg_latency6', models.IntegerField(default=0)),
            ],
        ),
        migrations.RenameField(
            model_name='test',
            old_name='completed_at',
            new_name='finished_at',
        ),
        migrations.RemoveField(
            model_name='response',
            name='is_correct',
        ),
        migrations.RemoveField(
            model_name='response',
            name='latency',
        ),
        migrations.RemoveField(
            model_name='response',
            name='response',
        ),
        migrations.RemoveField(
            model_name='result',
            name='age',
        ),
        migrations.AddField(
            model_name='response',
            name='response_posistion',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='response',
            name='time_submitted',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='result',
            name='ans1',
            field=models.CharField(default='', max_length=6),
        ),
        migrations.AddField(
            model_name='result',
            name='ans2',
            field=models.CharField(default='', max_length=6),
        ),
        migrations.AddField(
            model_name='result',
            name='ans3',
            field=models.CharField(default='', max_length=6),
        ),
        migrations.AddField(
            model_name='result',
            name='ans4',
            field=models.CharField(default='', max_length=6),
        ),
        migrations.AddField(
            model_name='result',
            name='ans5',
            field=models.CharField(default='', max_length=6),
        ),
        migrations.AddField(
            model_name='result',
            name='ans6',
            field=models.CharField(default='', max_length=6),
        ),
        migrations.AddField(
            model_name='stimulus',
            name='stimulus_type',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AddField(
            model_name='test',
            name='age',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='test',
            name='started_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='result',
            name='amount_correct',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='result',
            name='avg_latency1',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='result',
            name='avg_latency2',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='result',
            name='avg_latency3',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='result',
            name='avg_latency4',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='result',
            name='avg_latency5',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='result',
            name='avg_latency6',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='stimulus',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='permission_lvl',
            field=models.IntegerField(default=0),
        ),
    ]
