# Generated by Django 5.1.2 on 2024-10-12 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_rename_avg_latency1_result_latency1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aggreagate',
            old_name='avg_latency1',
            new_name='avg_fourd_latency_1',
        ),
        migrations.RenameField(
            model_name='aggreagate',
            old_name='avg_latency2',
            new_name='avg_fourd_latency_2',
        ),
        migrations.RenameField(
            model_name='aggreagate',
            old_name='avg_latency3',
            new_name='avg_fourd_latency_3',
        ),
        migrations.RenameField(
            model_name='aggreagate',
            old_name='avg_latency4',
            new_name='avg_fourd_latency_4',
        ),
        migrations.RenameField(
            model_name='aggreagate',
            old_name='avg_latency5',
            new_name='avg_fourd_latency_5',
        ),
        migrations.RenameField(
            model_name='aggreagate',
            old_name='avg_latency6',
            new_name='avg_fourd_latency_6',
        ),
        migrations.RenameField(
            model_name='result',
            old_name='latency1',
            new_name='fivedigit_latency_1',
        ),
        migrations.RenameField(
            model_name='result',
            old_name='latency2',
            new_name='fivedigit_latency_2',
        ),
        migrations.RenameField(
            model_name='result',
            old_name='latency3',
            new_name='fivedigit_latency_3',
        ),
        migrations.RenameField(
            model_name='result',
            old_name='latency4',
            new_name='fivemixed_latency_1',
        ),
        migrations.RenameField(
            model_name='result',
            old_name='latency5',
            new_name='fivemixed_latency_2',
        ),
        migrations.RenameField(
            model_name='result',
            old_name='latency6',
            new_name='fivemixed_latency_3',
        ),
        migrations.RemoveField(
            model_name='result',
            name='ans1',
        ),
        migrations.RemoveField(
            model_name='result',
            name='ans2',
        ),
        migrations.RemoveField(
            model_name='result',
            name='ans3',
        ),
        migrations.RemoveField(
            model_name='result',
            name='ans4',
        ),
        migrations.RemoveField(
            model_name='result',
            name='ans5',
        ),
        migrations.RemoveField(
            model_name='result',
            name='ans6',
        ),
        migrations.AddField(
            model_name='result',
            name='fivedigit_accuracy_1',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='result',
            name='fivedigit_accuracy_2',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='result',
            name='fivedigit_accuracy_3',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='result',
            name='fivemixed_accuracy_1',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='result',
            name='fivemixed_accuracy_2',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='result',
            name='fivemixed_accuracy_3',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='result',
            name='fourdigit_accuracy_1',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='result',
            name='fourdigit_accuracy_2',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='result',
            name='fourdigit_accuracy_3',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='result',
            name='fourdigit_latency_1',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='result',
            name='fourdigit_latency_2',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='result',
            name='fourdigit_latency_3',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='result',
            name='fourmixed_accuracy_1',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='result',
            name='fourmixed_accuracy_2',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='result',
            name='fourmixed_accuracy_3',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='result',
            name='fourmixed_latency_1',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='result',
            name='fourmixed_latency_2',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='result',
            name='fourmixed_latency_3',
            field=models.IntegerField(default=0),
        ),
    ]
