# Generated by Django 5.1.2 on 2024-10-12 05:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_rename_avg_latency1_aggreagate_avg_fourd_latency_1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stimulus_Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stimulus_type', models.CharField(default='', max_length=15)),
            ],
        ),
        migrations.RemoveField(
            model_name='stimulus',
            name='order',
        ),
        migrations.AlterField(
            model_name='stimulus',
            name='stimulus_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='website.stimulus_type'),
        ),
    ]
