# Generated by Django 5.1.1 on 2024-10-08 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='link',
            field=models.CharField(max_length=100, null=True, verbose_name='ppst.com/XsCfGu'),
        ),
    ]
