# Generated by Django 5.1.2 on 2024-10-12 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_stimulus_type_remove_stimulus_order_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aggreagate',
            old_name='avg_fourd_latency_1',
            new_name='avg_fivedigit_latency_1',
        ),
        migrations.RenameField(
            model_name='aggreagate',
            old_name='avg_fourd_latency_2',
            new_name='avg_fivedigit_latency_2',
        ),
        migrations.RenameField(
            model_name='aggreagate',
            old_name='avg_fourd_latency_3',
            new_name='avg_fivedigit_latency_3',
        ),
        migrations.RenameField(
            model_name='aggreagate',
            old_name='avg_fourd_latency_4',
            new_name='avg_fivemixed_latency_1',
        ),
        migrations.RenameField(
            model_name='aggreagate',
            old_name='avg_fourd_latency_5',
            new_name='avg_fivemixed_latency_2',
        ),
        migrations.RenameField(
            model_name='aggreagate',
            old_name='avg_fourd_latency_6',
            new_name='avg_fivemixed_latency_3',
        ),
        migrations.AddField(
            model_name='aggreagate',
            name='avg_fivedigit_accuracy_1',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='aggreagate',
            name='avg_fivedigit_accuracy_2',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='aggreagate',
            name='avg_fivedigit_accuracy_3',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='aggreagate',
            name='avg_fivemixed_accuracy_1',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='aggreagate',
            name='avg_fivemixed_accuracy_2',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='aggreagate',
            name='avg_fivemixed_accuracy_3',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='aggreagate',
            name='avg_fourdigit_accuracy_1',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='aggreagate',
            name='avg_fourdigit_accuracy_2',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='aggreagate',
            name='avg_fourdigit_accuracy_3',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='aggreagate',
            name='avg_fourdigit_latency_1',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='aggreagate',
            name='avg_fourdigit_latency_2',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='aggreagate',
            name='avg_fourdigit_latency_3',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='aggreagate',
            name='avg_fourmixed_accuracy_1',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='aggreagate',
            name='avg_fourmixed_accuracy_2',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='aggreagate',
            name='avg_fourmixed_accuracy_3',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='aggreagate',
            name='avg_fourmixed_latency_1',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='aggreagate',
            name='avg_fourmixed_latency_2',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='aggreagate',
            name='avg_fourmixed_latency_3',
            field=models.IntegerField(default=0),
        ),
    ]
