# Generated by Django 5.1.2 on 2024-10-12 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_rename_avg_fourd_latency_1_aggreagate_avg_fivedigit_latency_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='response',
            field=models.CharField(default='', max_length=5),
        ),
    ]
