# Generated by Django 5.1.1 on 2024-10-08 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_alter_test_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='completed_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='test',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='test',
            name='link',
            field=models.CharField(max_length=100, null=True, verbose_name='ppst.com/XZrQwy'),
        ),
    ]
