# Generated by Django 5.1.1 on 2024-10-25 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_alter_test_user_notification_ticket_delete_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='response',
            old_name='response_posistion',
            new_name='response_position',
        ),
    ]
