# Generated by Django 5.1.2 on 2024-10-25 09:15

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_alter_test_user_ticket_delete_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='response',
            old_name='response_posistion',
            new_name='response_position',
        ),
        migrations.AlterField(
            model_name='response',
            name='stimulus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.stimulus'),
        ),
        migrations.AlterField(
            model_name='response',
            name='time_submitted',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='test',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='test',
            name='link',
            field=models.CharField(max_length=8, unique=True),
        ),
        migrations.AlterField(
            model_name='test',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
