# Generated by Django 5.1.1 on 2024-10-08 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_alter_test_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='link',
            field=models.CharField(default='ppst.com/XoVfOY', max_length=100, null=True),
        ),
    ]
