# Generated by Django 5.1.2 on 2024-10-25 09:25

import website.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_rename_response_posistion_response_response_position_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='link',
            field=models.CharField(default=website.models.generate_link, max_length=8, unique=True),
        ),
    ]
